#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env.local
const envPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  envContent.split('\n').forEach((line: string) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;

    const [key, ...valueParts] = trimmed.split('=');
    const value = valueParts.join('=');
    if (key && value) {
      process.env[key.trim()] = value.trim().replace(/^['"]|['"]$/g, '');
    }
  });
}

const url = process.env.VITE_SUPABASE_URL || 'https://qcvnfvbzxbnrquxtjihp.supabase.co';
const key = process.env.VITE_SUPABASE_ANON_KEY;

// Release builds MUST target production regardless of what .env.local says.
// `npm run build:chrome` / `build:firefox` set BUILD_TARGET=release, which pins
// API_ENV to production. Only the explicit `:dev` scripts (or a bare
// `npm run build` with API_ENV=dev in .env.local) can produce a dev-targeted build.
const isReleaseBuild = process.env.BUILD_TARGET === 'release';
const requestedEnv = process.env.API_ENV || 'production';

if (requestedEnv !== 'production' && requestedEnv !== 'dev') {
  throw new Error(`Invalid API_ENV="${requestedEnv}". Use "production" or "dev".`);
}

if (isReleaseBuild && requestedEnv !== 'production') {
  console.warn(
    `⚠️  Release build requested with API_ENV=${requestedEnv}. Forcing API_ENV=production.`
  );
}

const env: 'production' | 'dev' = isReleaseBuild ? 'production' : requestedEnv;

if (!key) {
  throw new Error('Missing VITE_SUPABASE_ANON_KEY. Add it to .env.local before building.');
}

console.log(
  `Building SignalizeAI (${isReleaseBuild ? 'release' : 'local'}) against the ${env} API.`
);

// Write config file that will be imported.
// GENERATED FILE - do not edit by hand and do not commit (see .gitignore).
// Endpoints are resolved here at build time so the shipped bundle contains
// literal URLs rather than a runtime switch that can be flipped by accident.
const apiBaseUrl =
  env === 'dev' ? 'https://dev-api.signalizeai.org' : 'https://api.signalizeai.org';
const websiteBaseUrl = env === 'dev' ? 'http://localhost:3000' : 'https://signalizeai.org';

const configContent = `// GENERATED BY build.ts - DO NOT EDIT.
// Switch to the dev API with: npm run build:chrome:dev (or API_ENV=dev in .env.local).
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(key)};

export const ENV: 'production' | 'dev' = ${JSON.stringify(env)};

export const API_BASE_URL = ${JSON.stringify(apiBaseUrl)};

export const WEBSITE_BASE_URL = ${JSON.stringify(websiteBaseUrl)};
`;

fs.writeFileSync(path.join(__dirname, 'src/config.ts'), configContent);

// Hard gate: a release artifact must never contain dev endpoints.
if (isReleaseBuild) {
  const written = fs.readFileSync(path.join(__dirname, 'src/config.ts'), 'utf-8');
  if (written.includes('dev-api.signalizeai.org') || written.includes('localhost')) {
    throw new Error('Release build produced a dev-targeted src/config.ts. Aborting.');
  }
}

// Clear previous output before rebuilding.
//
// esbuild code-splitting emits content-hashed chunk files, so without this the
// extension/ directory accumulates every chunk ever built. Those stale chunks
// get packaged with the release and, worse, chunks built while API_ENV=dev
// still contain the dev endpoints. Deleting them is what makes the release
// build's production-only guarantee actually hold for the shipped folder.
const outDir = path.join(__dirname, 'extension');
if (fs.existsSync(outDir)) {
  for (const entry of fs.readdirSync(outDir)) {
    if (entry.endsWith('.js') || entry.endsWith('.js.map')) {
      fs.rmSync(path.join(outDir, entry), { force: true });
    }
  }
} else {
  fs.mkdirSync(outDir, { recursive: true });
}

// Build supabase bundle from TypeScript
const cmd1 = `esbuild src/sidepanel-entry.ts --bundle --format=iife --minify --outfile=extension/supabase.bundle.js`;
execSync(cmd1, { stdio: 'inherit' });

// Build sidepanel from TypeScript
const cmd2 = `esbuild sidepanel.ts --bundle --platform=browser --format=esm --minify --tree-shaking=true --splitting --outdir=extension`;
execSync(cmd2, { stdio: 'inherit' });

// Build background script from TypeScript
const cmd3 = `esbuild background.ts --bundle --format=iife --minify --outfile=extension/background.js`;
execSync(cmd3, { stdio: 'inherit' });

// Build content scripts from TypeScript
const cmd4 = `esbuild content-auth-bridge.ts --bundle --format=iife --minify --outfile=extension/content-auth-bridge.js`;
execSync(cmd4, { stdio: 'inherit' });

const cmd5 = `esbuild content-extractor.ts --bundle --format=iife --minify --outfile=extension/content-extractor.js`;
execSync(cmd5, { stdio: 'inherit' });

// Build sidepanel-loader from TypeScript
const cmd6 = `esbuild sidepanel-loader.ts --bundle --format=iife --minify --outfile=extension/sidepanel-loader.js`;
execSync(cmd6, { stdio: 'inherit' });

console.log('✅ All TypeScript files compiled successfully!');
